### ISSUE TITLE
formatToParts

### ISSUE THREAD

**Issue by icambron** [yahoo/date-time-format-timezone#11]
Would you accept a PR that adds a similar TZ-aware wrapper for [formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts)?

**Comment by markandey** [comment]
yes ! please do! We were already planing to do this!

**Comment by icambron** [comment]
I may take a crack at this weekend, time permitting. It would presumably only work if the browser had an existing `formatToParts` impl, i.e. it's only shimming the zone part of it. Is that what you were thinking too?

**Comment by icambron** [comment]
This was really easy to implement (see [here](https://github.com/icambron/date-time-format-timezone/tree/add-format-to-parts)) but when I went to test it, I realized it I couldn't find a platform where `formatToParts()` is supported but zones are not. Besides the immediate issue of how to test it, it makes me wonder if this change is really necessary.

The one use case I found -- and how I tested my changes manually -- was to use Intl.js to polyfill `formatToParts` and then use `date-time-format-timezone` to add zone support to it. That does strike me as a real use case, but I have no idea how to integrate that into the testing framework here, nor how how common the need for it is in practice. Is that useful?

If so, I need some guidance on how to configure the tests to test that. If not, I'll close this ticket. And if there's some use case or way forward I'm missing, I'd love to hear about it.

**Comment by markandey** [comment]
@icambron 
Thanks for working on this. 
Yes this polyfill not suppose to implement formatToParts on its own. But must be ready to passthrough `formatToParts` if its supported by shimming timezone part of it.
this is only be possible in browsers which support `Intl.DateTimeFormat` via intl.js polyfill.
Give me sometime so that I can add tests for such cases. Then you can add tests for `formatToParts` and make and raise a Pull Request.

**Comment by icambron** [comment]
> Give me sometime so that I can add tests for such cases

Meaning, you'll add the test infrastructure to run tests in an environment already polyfilled by Intl.js? If so, that sounds good.

**Comment by markandey** [comment]
@icambron yes

**Comment by markandey** [comment]
@icambron 
Just added a test for ie10 in this [Pull Request#12 ](https://github.com/yahoo/date-time-format-timezone/pulls)
since 1e10 ,[ does not have support for intl](http://caniuse.com/#feat=internationalization) it needs intl.js polyfill , this should be good test environment to formatToParts.

I have also added some test which should also test formatToParts implementation.

**Comment by markandey** [comment]
@icambron you can run ie10 on saucelabs, 
these test do not run locally by default 
use 

` grunt build karma:saucelabsTest `  
to run locally.  

this assumes that you have process.env.SAUCE_USERNAME and process.env.SAUCE_ACCESS_KEY are set.

**Comment by icambron** [comment]
@markandey That makes sense and I'm happy to integrate my code with but I'm missing one thing: what's the best way for me to add the Intl.js pollyfill to the IE10 run of tests?

**Comment by markandey** [comment]
@icambron its all added now! (i have intl.js as npm)
after my PR you would see formatToParts tests which are skipped , you un cover them and TDD to add your implementation

**Comment by icambron** [comment]
OK, cool, thanks! I'll give it a shot and post a PR.
